In [2]:
import numpy as np
import cv2

In [35]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")


In [36]:
image = cv2.imread('tej2.jpg')


In [37]:
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [38]:
faces = face_cascade.detectMultiScale(grayImage)
print(type(faces))
print(faces)

<class 'numpy.ndarray'>
[[615 232  67  67]
 [419 503  76  76]
 [452 307  59  59]
 [529 725  85  85]
 [663 576  71  71]
 [972 568  82  82]
 [  7 386  67  67]
 [802 278  65  65]
 [492 293  61  61]
 [139 419  53  53]]


In [39]:
print(faces)
print("Number of faces detected: " + str(faces.shape[0]))

[[615 232  67  67]
 [419 503  76  76]
 [452 307  59  59]
 [529 725  85  85]
 [663 576  71  71]
 [972 568  82  82]
 [  7 386  67  67]
 [802 278  65  65]
 [492 293  61  61]
 [139 419  53  53]]
Number of faces detected: 10


In [22]:
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)

In [23]:
cv2.rectangle(image, ((0,image.shape[0] -25)),(270, image.shape[0]), (255,255,255), -1)
cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0,0,0), 1)

array([[[132, 169,  99],
        [135, 172, 102],
        [138, 175, 105],
        ...,
        [243, 255, 255],
        [242, 254, 254],
        [236, 248, 248]],

       [[131, 168,  98],
        [133, 170, 100],
        [136, 173, 103],
        ...,
        [189, 201, 201],
        [244, 255, 255],
        [235, 247, 247]],

       [[130, 167,  97],
        [132, 169,  99],
        [134, 171, 101],
        ...,
        [ 97, 109, 109],
        [196, 208, 208],
        [227, 239, 239]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 87, 113, 153],
        [ 70,  95, 135],
        [ 57,  82, 122]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 63,  88, 130],
        [ 50,  75, 117],
        [ 37,  62, 104]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 99, 124, 166],
        [ 76, 101, 143],
        [ 49,  74, 116]]

In [24]:
cv2.imshow('Image with faces',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
### Experiment 

tup1 = ('physics', 'chemistry', 1997, 2000);
tup1

('physics', 'chemistry', 1997, 2000)

In [34]:
face_cascade_ext = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalcatface_extended.xml")